[package]
name = "to_vmt"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
proc-macro2 = "1.0.92"
quote = "1.0.37"
smt2parser = { workspace = true }
syn = "2.0.90"
vmt_macros = { path = "vmt_macros" }
vmtil = { path = "vmtil" }
yardbird = { path = ".." }
z3 = { workspace = true }
