#!/usr/bin/env python3
"""
Unsat Core Analyzer for Yardbird

This utility analyzes unsat cores from yardbird BMC proofs to identify which
instantiations were most useful in the proof.

Usage:
    # Analyze yardbird's tracked output (fast, accurate)
    python analyze_core.py --core-json unsat_core.json
"""

import argparse
import json
import sys
from pathlib import Path
from collections import Counter
from typing import Dict
import re


def load_unsat_core_json(path: Path) -> Dict:
    """Load unsat core data from JSON file generated by yardbird."""
    with open(path) as f:
        return json.load(f)


def analyze_core_json(data: Dict) -> None:
    """Analyze and display statistics from unsat core JSON."""
    print("=" * 60)
    print("UNSAT CORE ANALYSIS")
    print("=" * 60)
    print()

    total = data["total_instantiations"]
    core_size = data["core_size"]
    percentage = (core_size / total * 100) if total > 0 else 0

    print(f"Total instantiations tracked: {total}")
    print(f"Instantiations in unsat core: {core_size}")
    print(f"Core percentage: {percentage:.1f}%")
    print()

    if core_size == 0:
        print(
            "No instantiations in core - the proof didn't require any tracked instantiations."
        )
        return

    # Analyze core instantiations
    core_insts = data["core_instantiations"]

    # Depth analysis if labels contain depth info
    print("=" * 60)
    print("DEPTH DISTRIBUTION")
    print("=" * 60)
    print()

    depth_counts = Counter()
    for inst in core_insts:
        label = inst["label"]
        # Extract depth from label if it contains "depth_N"
        match = re.search(r"depth_(\d+)", label)
        if match:
            depth = int(match.group(1))
            depth_counts[depth] += 1

    if depth_counts:
        print("Instantiations by BMC depth:")
        for depth in sorted(depth_counts.keys()):
            count = depth_counts[depth]
            bar = "█" * (count // 2)
            print(f"  Depth {depth:2d}: {count:4d}  {bar}")
    else:
        print("  (Depth information not available in labels)")
    print()

    # Show first few core instantiations
    print("=" * 80)
    print("SAMPLE CORE INSTANTIATIONS (first 10)")
    print("=" * 80)
    print()

    for i, inst in enumerate(core_insts[:10], 1):
        print(f"{i}. [{inst['label']}]")
        print(f"   {inst['term']}")
        print()


def main():
    parser = argparse.ArgumentParser(
        description="Analyze unsat cores from yardbird BMC proofs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    parser.add_argument(
        "--core-json",
        type=Path,
        help="Path to unsat core JSON file from yardbird (--dump-unsat-core)",
    )

    args = parser.parse_args()

    if not args.core_json:
        parser.error("Must specify either --core-json")

    try:
        data = load_unsat_core_json(args.core_json)
        analyze_core_json(data)

    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        if args.verbose:
            import traceback

            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
