[package]
name = "yardbird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
egg = "0.9.5"
env_logger = "0.11.5"
log = "0.4.22"
smt2parser = { path = "./smt2parser", version = "0.6.1" }
z3 = "0.12.1"

[workspace]
members = [
    "smt2parser",
]
