/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BamlVideoUrl {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "media_type", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
}

impl BamlVideoUrl {
    pub fn new(url: String) -> BamlVideoUrl {
        BamlVideoUrl {
            url,
            media_type: None,
        }
    }
}
