/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BamlOptionsClientRegistry {
    #[serde(rename = "clients")]
    pub clients: Vec<models::ClientProperty>,
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<String>,
}

impl BamlOptionsClientRegistry {
    pub fn new(clients: Vec<models::ClientProperty>) -> BamlOptionsClientRegistry {
        BamlOptionsClientRegistry {
            clients,
            primary: None,
        }
    }
}
