/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BamlAudio {
    BamlAudioBase64(Box<models::BamlAudioBase64>),
    BamlAudioUrl(Box<models::BamlAudioUrl>),
}

impl Default for BamlAudio {
    fn default() -> Self {
        Self::BamlAudioBase64(Default::default())
    }
}
