/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BamlVideo {
    BamlVideoBase64(Box<models::BamlVideoBase64>),
    BamlVideoUrl(Box<models::BamlVideoUrl>),
}

impl Default for BamlVideo {
    fn default() -> Self {
        Self::BamlVideoBase64(Default::default())
    }
}
