/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BamlPdf {
    BamlPdfBase64(Box<models::BamlPdfBase64>),
    BamlPdfUrl(Box<models::BamlPdfUrl>),
}

impl Default for BamlPdf {
    fn default() -> Self {
        Self::BamlPdfBase64(Default::default())
    }
}
