/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BamlImage {
    BamlImageBase64(Box<models::BamlImageBase64>),
    BamlImageUrl(Box<models::BamlImageUrl>),
}

impl Default for BamlImage {
    fn default() -> Self {
        Self::BamlImageBase64(Default::default())
    }
}
