/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BamlVideoBase64 {
    #[serde(rename = "base64")]
    pub base64: String,
    #[serde(rename = "media_type", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<String>,
}

impl BamlVideoBase64 {
    pub fn new(base64: String) -> BamlVideoBase64 {
        BamlVideoBase64 {
            base64,
            media_type: None,
        }
    }
}
