/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BamlOptions {
    #[serde(rename = "client_registry")]
    pub client_registry: Box<models::BamlOptionsClientRegistry>,
}

impl BamlOptions {
    pub fn new(client_registry: models::BamlOptionsClientRegistry) -> BamlOptions {
        BamlOptions {
            client_registry: Box::new(client_registry),
        }
    }
}
