/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Check {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "expr")]
    pub expr: String,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl Check {
    pub fn new(name: String, expr: String) -> Check {
        Check {
            name,
            expr,
            status: None,
        }
    }
}
