/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientProperty {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "options")]
    pub options: std::collections::HashMap<String, serde_json::Value>,
}

impl ClientProperty {
    pub fn new(
        name: String,
        provider: String,
        options: std::collections::HashMap<String, serde_json::Value>,
    ) -> ClientProperty {
        ClientProperty {
            name,
            provider,
            options,
        }
    }
}
