/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvariantSuggestions {
    #[serde(rename = "analysis")]
    pub analysis: String,
    #[serde(rename = "candidates")]
    pub candidates: Vec<models::InvariantCandidate>,
    #[serde(rename = "strategy_hints")]
    pub strategy_hints: Vec<String>,
}

impl InvariantSuggestions {
    pub fn new(
        analysis: String,
        candidates: Vec<models::InvariantCandidate>,
        strategy_hints: Vec<String>,
    ) -> InvariantSuggestions {
        InvariantSuggestions {
            analysis,
            candidates,
            strategy_hints,
        }
    }
}
