/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvariantCandidate {
    #[serde(rename = "formula")]
    pub formula: String,
    #[serde(rename = "invariant_type")]
    pub invariant_type: String,
}

impl InvariantCandidate {
    pub fn new(formula: String, invariant_type: String) -> InvariantCandidate {
        InvariantCandidate {
            formula,
            invariant_type,
        }
    }
}
