/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvariantSuggestions {
    #[serde(rename = "candidate_formula")]
    pub candidate_formula: String,
}

impl InvariantSuggestions {
    pub fn new(candidate_formula: String) -> InvariantSuggestions {
        InvariantSuggestions { candidate_formula }
    }
}
