/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProposeInvariantRequest {
    #[serde(rename = "request")]
    pub request: Box<models::VerificationRequest>,
    #[serde(rename = "__baml_options__", skip_serializing_if = "Option::is_none")]
    pub __baml_options__: Option<Box<models::BamlOptions>>,
}

impl ProposeInvariantRequest {
    pub fn new(request: models::VerificationRequest) -> ProposeInvariantRequest {
        ProposeInvariantRequest {
            request: Box::new(request),
            __baml_options__: None,
        }
    }
}
