/*
 * baml-cli serve
 *
 * baml-cli serve
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerificationRequest {
    #[serde(rename = "analysis_type")]
    pub analysis_type: models::AnalysisType,
    #[serde(rename = "context")]
    pub context: Box<models::VerificationContext>,
    #[serde(rename = "counterexample", skip_serializing_if = "Option::is_none")]
    pub counterexample: Option<String>,
    #[serde(rename = "current_strategy", skip_serializing_if = "Option::is_none")]
    pub current_strategy: Option<String>,
    #[serde(rename = "failed_invariants")]
    pub failed_invariants: Vec<String>,
}

impl VerificationRequest {
    pub fn new(
        analysis_type: models::AnalysisType,
        context: models::VerificationContext,
        failed_invariants: Vec<String>,
    ) -> VerificationRequest {
        VerificationRequest {
            analysis_type,
            context: Box::new(context),
            counterexample: None,
            current_strategy: None,
            failed_invariants,
        }
    }
}
