pub mod array_axioms;
pub mod array_dataflow;
pub mod array_egraph_builder;
mod array_expr_parser;
mod array_grounding;
pub mod array_rule_instantiator;
pub mod array_term_extractor;
pub mod candidate_scope;
pub mod instantiation_candidate;
pub mod transition_guard_instantiator;
