/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ArtifactsArtImport } from './routes/artifacts/$art'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ArtifactsArtRoute = ArtifactsArtImport.update({
  id: '/artifacts/$art',
  path: '/artifacts/$art',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/artifacts/$art': {
      id: '/artifacts/$art'
      path: '/artifacts/$art'
      fullPath: '/artifacts/$art'
      preLoaderRoute: typeof ArtifactsArtImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/artifacts/$art': typeof ArtifactsArtRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/artifacts/$art': typeof ArtifactsArtRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/artifacts/$art': typeof ArtifactsArtRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artifacts/$art'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artifacts/$art'
  id: '__root__' | '/' | '/artifacts/$art'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ArtifactsArtRoute: typeof ArtifactsArtRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ArtifactsArtRoute: ArtifactsArtRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/artifacts/$art"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/artifacts/$art": {
      "filePath": "artifacts/$art.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
