name: Garden

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust 1.89.0
        uses: dtolnay/rust-toolchain@1.89.0
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release -p garden
      - name: Run benchmarks
        run: ./target/release/garden examples/array -o garden.json --strategy abstract --strategy concrete --depth 10
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.head_ref }}-${{ github.sha }}
          path: garden.json
